//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zarpa.Client.Resources.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Zarpa.Client.Resources.Languages.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string AciertosFormat {
            get {
                return ResourceManager.GetString("AciertosFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string AddValidMailMessage {
            get {
                return ResourceManager.GetString("AddValidMailMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string AlreadyHaveAccountQuestion {
            get {
                return ResourceManager.GetString("AlreadyHaveAccountQuestion", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string AppTagline {
            get {
                return ResourceManager.GetString("AppTagline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string AppleAuthFailedError {
            get {
                return ResourceManager.GetString("AppleAuthFailedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string BackToSignIn {
            get {
                return ResourceManager.GetString("BackToSignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string BackToTopics {
            get {
                return ResourceManager.GetString("BackToTopics", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string CheckSpamFolderAdvice {
            get {
                return ResourceManager.GetString("CheckSpamFolderAdvice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string CodeCannotBeEmpty {
            get {
                return ResourceManager.GetString("CodeCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string CodeMustBe6DigitsLong {
            get {
                return ResourceManager.GetString("CodeMustBe6DigitsLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string CodeMustContainOnlyNumbers {
            get {
                return ResourceManager.GetString("CodeMustContainOnlyNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string ComingSoon {
            get {
                return ResourceManager.GetString("ComingSoon", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string CompletedSuffix {
            get {
                return ResourceManager.GetString("CompletedSuffix", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string CorrectFeedback {
            get {
                return ResourceManager.GetString("CorrectFeedback", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string CreateNewAccount {
            get {
                return ResourceManager.GetString("CreateNewAccount", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string EmailAlreadyExistsError {
            get {
                return ResourceManager.GetString("EmailAlreadyExistsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string EmailHasBeenSent {
            get {
                return ResourceManager.GetString("EmailHasBeenSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string EmailNotFoundError {
            get {
                return ResourceManager.GetString("EmailNotFoundError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string EmailPlaceholder {
            get {
                return ResourceManager.GetString("EmailPlaceholder", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string EnterEmailForgotPasswordMessage {
            get {
                return ResourceManager.GetString("EnterEmailForgotPasswordMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string SignInLink {
            get {
                return ResourceManager.GetString("SignInLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string ExamSimulationDescription {
            get {
                return ResourceManager.GetString("ExamSimulationDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string ExamSimulationTitle {
            get {
                return ResourceManager.GetString("ExamSimulationTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string ExplanationLabel {
            get {
                return ResourceManager.GetString("ExplanationLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string FacebookAuthFailedError {
            get {
                return ResourceManager.GetString("FacebookAuthFailedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string FacebookNoEmailError {
            get {
                return ResourceManager.GetString("FacebookNoEmailError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string FieldNameNotValidMessage {
            get {
                return ResourceManager.GetString("FieldNameNotValidMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string FallosFormat {
            get {
                return ResourceManager.GetString("FallosFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string ForgotPassword {
            get {
                return ResourceManager.GetString("ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string ForgotPasswordPage {
            get {
                return ResourceManager.GetString("ForgotPasswordPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string GlobalProgressLabel {
            get {
                return ResourceManager.GetString("GlobalProgressLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string GoogleAuthFailedError {
            get {
                return ResourceManager.GetString("GoogleAuthFailedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string HomePage {
            get {
                return ResourceManager.GetString("HomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string IncorrectFeedback {
            get {
                return ResourceManager.GetString("IncorrectFeedback", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string IncorrectPasswordError {
            get {
                return ResourceManager.GetString("IncorrectPasswordError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string InvalidEmailAddress {
            get {
                return ResourceManager.GetString("InvalidEmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string LearningModeDescription {
            get {
                return ResourceManager.GetString("LearningModeDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string LearningModeTitle {
            get {
                return ResourceManager.GetString("LearningModeTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string NamePlaceholder {
            get {
                return ResourceManager.GetString("NamePlaceholder", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string NextQuestion {
            get {
                return ResourceManager.GetString("NextQuestion", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string NoAccountQuestion {
            get {
                return ResourceManager.GetString("NoAccountQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string NoQuestionsInTopic {
            get {
                return ResourceManager.GetString("NoQuestionsInTopic", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string OrContinueWith {
            get {
                return ResourceManager.GetString("OrContinueWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string PasswordContainsSpaces {
            get {
                return ResourceManager.GetString("PasswordContainsSpaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string PasswordPlaceholder {
            get {
                return ResourceManager.GetString("PasswordPlaceholder", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string PasswordTooShort {
            get {
                return ResourceManager.GetString("PasswordTooShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string PasswordsDoNotMatch {
            get {
                return ResourceManager.GetString("PasswordsDoNotMatch", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string PracticeByTopicTitle {
            get {
                return ResourceManager.GetString("PracticeByTopicTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string PracticeLikeExamTitle {
            get {
                return ResourceManager.GetString("PracticeLikeExamTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string QuestionProgressFormat {
            get {
                return ResourceManager.GetString("QuestionProgressFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string QuestionsCountFormat {
            get {
                return ResourceManager.GetString("QuestionsCountFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string SelectLicenseFirst {
            get {
                return ResourceManager.GetString("SelectLicenseFirst", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string SignIn {
            get {
                return ResourceManager.GetString("SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string SignInButton {
            get {
                return ResourceManager.GetString("SignInButton", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string SignUp {
            get {
                return ResourceManager.GetString("SignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string SigninUnknownError {
            get {
                return ResourceManager.GetString("SigninUnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string SignupHeading {
            get {
                return ResourceManager.GetString("SignupHeading", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string SignupSubtitle {
            get {
                return ResourceManager.GetString("SignupSubtitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string SignupUnknownError {
            get {
                return ResourceManager.GetString("SignupUnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string Signout {
            get {
                return ResourceManager.GetString("Signout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string StartSimulation {
            get {
                return ResourceManager.GetString("StartSimulation", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string TabProfile {
            get {
                return ResourceManager.GetString("TabProfile", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string TabStudy {
            get {
                return ResourceManager.GetString("TabStudy", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string TabTests {
            get {
                return ResourceManager.GetString("TabTests", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string TermsAndConditionsAgreement {
            get {
                return ResourceManager.GetString("TermsAndConditionsAgreement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string TopicCompleted {
            get {
                return ResourceManager.GetString("TopicCompleted", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string TopicSelectionDescription {
            get {
                return ResourceManager.GetString("TopicSelectionDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string TopicSelectionOverline {
            get {
                return ResourceManager.GetString("TopicSelectionOverline", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string TopicSelectionTitle {
            get {
                return ResourceManager.GetString("TopicSelectionTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string UnknownError {
            get {
                return ResourceManager.GetString("UnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string UseSocialSigninError {
            get {
                return ResourceManager.GetString("UseSocialSigninError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string UserBlocked {
            get {
                return ResourceManager.GetString("UserBlocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string UserDoesNotExistError {
            get {
                return ResourceManager.GetString("UserDoesNotExistError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string ValidateYourEmail {
            get {
                return ResourceManager.GetString("ValidateYourEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string ValidationCode {
            get {
                return ResourceManager.GetString("ValidationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string VerificationCode {
            get {
                return ResourceManager.GetString("VerificationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string YourLicenseLabel {
            get {
                return ResourceManager.GetString("YourLicenseLabel", resourceCulture);
            }
        }
    }
}
