//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zarpa.Client.Resources.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Zarpa.Client.Resources.Languages.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string AddValidMailMessage {
            get {
                return ResourceManager.GetString("AddValidMailMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string AppTagline {
            get {
                return ResourceManager.GetString("AppTagline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string AppleAuthFailedError {
            get {
                return ResourceManager.GetString("AppleAuthFailedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string BackToSignIn {
            get {
                return ResourceManager.GetString("BackToSignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string CheckSpamFolderAdvice {
            get {
                return ResourceManager.GetString("CheckSpamFolderAdvice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string CodeCannotBeEmpty {
            get {
                return ResourceManager.GetString("CodeCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string CodeMustBe6DigitsLong {
            get {
                return ResourceManager.GetString("CodeMustBe6DigitsLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string CodeMustContainOnlyNumbers {
            get {
                return ResourceManager.GetString("CodeMustContainOnlyNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string EmailAlreadyExistsError {
            get {
                return ResourceManager.GetString("EmailAlreadyExistsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string EmailHasBeenSent {
            get {
                return ResourceManager.GetString("EmailHasBeenSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string EmailNotFoundError {
            get {
                return ResourceManager.GetString("EmailNotFoundError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string EnterEmailForgotPasswordMessage {
            get {
                return ResourceManager.GetString("EnterEmailForgotPasswordMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string ExistingUserSignIn {
            get {
                return ResourceManager.GetString("ExistingUserSignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string FacebookAuthFailedError {
            get {
                return ResourceManager.GetString("FacebookAuthFailedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string FacebookNoEmailError {
            get {
                return ResourceManager.GetString("FacebookNoEmailError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string FieldNameNotValidMessage {
            get {
                return ResourceManager.GetString("FieldNameNotValidMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string ForgotPassword {
            get {
                return ResourceManager.GetString("ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string ForgotPasswordPage {
            get {
                return ResourceManager.GetString("ForgotPasswordPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string GoogleAuthFailedError {
            get {
                return ResourceManager.GetString("GoogleAuthFailedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string HomePage {
            get {
                return ResourceManager.GetString("HomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string IncorrectPasswordError {
            get {
                return ResourceManager.GetString("IncorrectPasswordError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string InvalidEmailAddress {
            get {
                return ResourceManager.GetString("InvalidEmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string NewUserSignUp {
            get {
                return ResourceManager.GetString("NewUserSignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string OrContinueWith {
            get {
                return ResourceManager.GetString("OrContinueWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string PasswordContainsSpaces {
            get {
                return ResourceManager.GetString("PasswordContainsSpaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string PasswordTooShort {
            get {
                return ResourceManager.GetString("PasswordTooShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string SignIn {
            get {
                return ResourceManager.GetString("SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string SignUp {
            get {
                return ResourceManager.GetString("SignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string SigninUnknownError {
            get {
                return ResourceManager.GetString("SigninUnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string SignupUnknownError {
            get {
                return ResourceManager.GetString("SignupUnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string Signout {
            get {
                return ResourceManager.GetString("Signout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string TermsAndConditionsAgreement {
            get {
                return ResourceManager.GetString("TermsAndConditionsAgreement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string UnknownError {
            get {
                return ResourceManager.GetString("UnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string UseSocialSigninError {
            get {
                return ResourceManager.GetString("UseSocialSigninError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string UserBlocked {
            get {
                return ResourceManager.GetString("UserBlocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string UserDoesNotExistError {
            get {
                return ResourceManager.GetString("UserDoesNotExistError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string ValidateYourEmail {
            get {
                return ResourceManager.GetString("ValidateYourEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string ValidationCode {
            get {
                return ResourceManager.GetString("ValidationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string VerificationCode {
            get {
                return ResourceManager.GetString("VerificationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
    }
}
