//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NavigationES.Client.Resources.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NavigationES.Client.Resources.Languages.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string AciertosFormat {
            get {
                return ResourceManager.GetString("AciertosFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string AciertosLabel {
            get {
                return ResourceManager.GetString("AciertosLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string AciertosSub {
            get {
                return ResourceManager.GetString("AciertosSub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string AddValidMailMessage {
            get {
                return ResourceManager.GetString("AddValidMailMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string AllQuestions {
            get {
                return ResourceManager.GetString("AllQuestions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string AlreadyHaveAccountQuestion {
            get {
                return ResourceManager.GetString("AlreadyHaveAccountQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string AnswersFormat {
            get {
                return ResourceManager.GetString("AnswersFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string AnswersNotArrivedFormat {
            get {
                return ResourceManager.GetString("AnswersNotArrivedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string AppTagline {
            get {
                return ResourceManager.GetString("AppTagline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string AppleAuthFailedError {
            get {
                return ResourceManager.GetString("AppleAuthFailedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string AprobadosLabel {
            get {
                return ResourceManager.GetString("AprobadosLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string Apto {
            get {
                return ResourceManager.GetString("Apto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string BackToExams {
            get {
                return ResourceManager.GetString("BackToExams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string BackToSignIn {
            get {
                return ResourceManager.GetString("BackToSignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string BackToTopics {
            get {
                return ResourceManager.GetString("BackToTopics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string CheckSpamFolderAdvice {
            get {
                return ResourceManager.GetString("CheckSpamFolderAdvice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string ChooseComunidadTagline {
            get {
                return ResourceManager.GetString("ChooseComunidadTagline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string ChooseLicenseTagline {
            get {
                return ResourceManager.GetString("ChooseLicenseTagline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string CodeCannotBeEmpty {
            get {
                return ResourceManager.GetString("CodeCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string CodeMustBe6DigitsLong {
            get {
                return ResourceManager.GetString("CodeMustBe6DigitsLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string CodeMustContainOnlyNumbers {
            get {
                return ResourceManager.GetString("CodeMustContainOnlyNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string ComingSoon {
            get {
                return ResourceManager.GetString("ComingSoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string CompletedSuffix {
            get {
                return ResourceManager.GetString("CompletedSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string ComunidadPlaceholder {
            get {
                return ResourceManager.GetString("ComunidadPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string ContinueExam {
            get {
                return ResourceManager.GetString("ContinueExam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string CorrectFeedback {
            get {
                return ResourceManager.GetString("CorrectFeedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string CreateNewAccount {
            get {
                return ResourceManager.GetString("CreateNewAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string DangerZoneTitle {
            get {
                return ResourceManager.GetString("DangerZoneTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string DeleteAccount {
            get {
                return ResourceManager.GetString("DeleteAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string DeleteAccountConfirm {
            get {
                return ResourceManager.GetString("DeleteAccountConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string DeleteAccountWarning {
            get {
                return ResourceManager.GetString("DeleteAccountWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string Deleting {
            get {
                return ResourceManager.GetString("Deleting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string Deliver {
            get {
                return ResourceManager.GetString("Deliver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string EditName {
            get {
                return ResourceManager.GetString("EditName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string EmailAlreadyExistsError {
            get {
                return ResourceManager.GetString("EmailAlreadyExistsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string EmailHasBeenSent {
            get {
                return ResourceManager.GetString("EmailHasBeenSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string EmailNotFoundError {
            get {
                return ResourceManager.GetString("EmailNotFoundError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string EmailNotVerifiedTag {
            get {
                return ResourceManager.GetString("EmailNotVerifiedTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string EmailPlaceholder {
            get {
                return ResourceManager.GetString("EmailPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string EmailVerifiedTag {
            get {
                return ResourceManager.GetString("EmailVerifiedTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string EnterEmailForgotPasswordMessage {
            get {
                return ResourceManager.GetString("EnterEmailForgotPasswordMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string ErrorsByTopic {
            get {
                return ResourceManager.GetString("ErrorsByTopic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string ErrorsFormat {
            get {
                return ResourceManager.GetString("ErrorsFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string ErrorsTotalLabel {
            get {
                return ResourceManager.GetString("ErrorsTotalLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string ExamDefaultTitle {
            get {
                return ResourceManager.GetString("ExamDefaultTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string ExamMetaFormat {
            get {
                return ResourceManager.GetString("ExamMetaFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string ExamSimulationDescription {
            get {
                return ResourceManager.GetString("ExamSimulationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string ExamSimulationTitle {
            get {
                return ResourceManager.GetString("ExamSimulationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string ExamsHeroLabel {
            get {
                return ResourceManager.GetString("ExamsHeroLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string ExamsTaglinePrefix {
            get {
                return ResourceManager.GetString("ExamsTaglinePrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string ExamsTaglineSuffix {
            get {
                return ResourceManager.GetString("ExamsTaglineSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string ExitAndDelete {
            get {
                return ResourceManager.GetString("ExitAndDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string ExitExamMessage {
            get {
                return ResourceManager.GetString("ExitExamMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string ExitExamTitle {
            get {
                return ResourceManager.GetString("ExitExamTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string ExplanationLabel {
            get {
                return ResourceManager.GetString("ExplanationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string FacebookAuthFailedError {
            get {
                return ResourceManager.GetString("FacebookAuthFailedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string FacebookNoEmailError {
            get {
                return ResourceManager.GetString("FacebookNoEmailError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string FailedQuestions {
            get {
                return ResourceManager.GetString("FailedQuestions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string FallosFormat {
            get {
                return ResourceManager.GetString("FallosFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string FallosLabel {
            get {
                return ResourceManager.GetString("FallosLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string FieldNameNotValidMessage {
            get {
                return ResourceManager.GetString("FieldNameNotValidMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string Figure {
            get {
                return ResourceManager.GetString("Figure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string FinishExam {
            get {
                return ResourceManager.GetString("FinishExam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string FinishExamMessage {
            get {
                return ResourceManager.GetString("FinishExamMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string FinishExamUnansweredFormat {
            get {
                return ResourceManager.GetString("FinishExamUnansweredFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string ForgotPassword {
            get {
                return ResourceManager.GetString("ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string ForgotPasswordPage {
            get {
                return ResourceManager.GetString("ForgotPasswordPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string GlobalProgressLabel {
            get {
                return ResourceManager.GetString("GlobalProgressLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string GoToExams {
            get {
                return ResourceManager.GetString("GoToExams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string GoToTopics {
            get {
                return ResourceManager.GetString("GoToTopics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string GoogleAuthFailedError {
            get {
                return ResourceManager.GetString("GoogleAuthFailedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string HelloFormat {
            get {
                return ResourceManager.GetString("HelloFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string HomeExamsTitle {
            get {
                return ResourceManager.GetString("HomeExamsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string HomePage {
            get {
                return ResourceManager.GetString("HomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string HomeTopicsTitle {
            get {
                return ResourceManager.GetString("HomeTopicsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string IncorrectFeedback {
            get {
                return ResourceManager.GetString("IncorrectFeedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string IncorrectPasswordError {
            get {
                return ResourceManager.GetString("IncorrectPasswordError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string InvalidEmailAddress {
            get {
                return ResourceManager.GetString("InvalidEmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string LearningModeDescription {
            get {
                return ResourceManager.GetString("LearningModeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string LearningModeTitle {
            get {
                return ResourceManager.GetString("LearningModeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string ModelFormat {
            get {
                return ResourceManager.GetString("ModelFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string ModelUnique {
            get {
                return ResourceManager.GetString("ModelUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string NameNotValidError {
            get {
                return ResourceManager.GetString("NameNotValidError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string NamePlaceholder {
            get {
                return ResourceManager.GetString("NamePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string NameUpdated {
            get {
                return ResourceManager.GetString("NameUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string NextQuestion {
            get {
                return ResourceManager.GetString("NextQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string NextQuestionArrow {
            get {
                return ResourceManager.GetString("NextQuestionArrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string NoAccountQuestion {
            get {
                return ResourceManager.GetString("NoAccountQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string NoApto {
            get {
                return ResourceManager.GetString("NoApto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string NoAptosLabel {
            get {
                return ResourceManager.GetString("NoAptosLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string NoErrors {
            get {
                return ResourceManager.GetString("NoErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string NoExamsAvailable {
            get {
                return ResourceManager.GetString("NoExamsAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string NoQuestionsInTopic {
            get {
                return ResourceManager.GetString("NoQuestionsInTopic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string NoQuestionsShort {
            get {
                return ResourceManager.GetString("NoQuestionsShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string OfSeparator {
            get {
                return ResourceManager.GetString("OfSeparator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string OfficialExamsOfFormat {
            get {
                return ResourceManager.GetString("OfficialExamsOfFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string OneAnswer {
            get {
                return ResourceManager.GetString("OneAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string OneAnswerNotArrived {
            get {
                return ResourceManager.GetString("OneAnswerNotArrived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string OneError {
            get {
                return ResourceManager.GetString("OneError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string OrContinueWith {
            get {
                return ResourceManager.GetString("OrContinueWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string PasswordContainsSpaces {
            get {
                return ResourceManager.GetString("PasswordContainsSpaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string PasswordPlaceholder {
            get {
                return ResourceManager.GetString("PasswordPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string PasswordTooShort {
            get {
                return ResourceManager.GetString("PasswordTooShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string PasswordsDoNotMatch {
            get {
                return ResourceManager.GetString("PasswordsDoNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string PersonalDataTitle {
            get {
                return ResourceManager.GetString("PersonalDataTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string PracticeByTopicTitle {
            get {
                return ResourceManager.GetString("PracticeByTopicTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string PracticeLikeExamTitle {
            get {
                return ResourceManager.GetString("PracticeLikeExamTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string PreviousQuestion {
            get {
                return ResourceManager.GetString("PreviousQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string ProfileComunidadTitle {
            get {
                return ResourceManager.GetString("ProfileComunidadTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string ProfileEmailLabel {
            get {
                return ResourceManager.GetString("ProfileEmailLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string ProfileNameLabel {
            get {
                return ResourceManager.GetString("ProfileNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string QuestionProgressFormat {
            get {
                return ResourceManager.GetString("QuestionProgressFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string QuestionsCountFormat {
            get {
                return ResourceManager.GetString("QuestionsCountFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string Restart {
            get {
                return ResourceManager.GetString("Restart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string RestartTopic {
            get {
                return ResourceManager.GetString("RestartTopic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string RestartTopicConfirmMessage {
            get {
                return ResourceManager.GetString("RestartTopicConfirmMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string SaveName {
            get {
                return ResourceManager.GetString("SaveName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string SavingName {
            get {
                return ResourceManager.GetString("SavingName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string SelectLicenseFirst {
            get {
                return ResourceManager.GetString("SelectLicenseFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string ShowAllQuestions {
            get {
                return ResourceManager.GetString("ShowAllQuestions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string ShowOnlyErrors {
            get {
                return ResourceManager.GetString("ShowOnlyErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string SignIn {
            get {
                return ResourceManager.GetString("SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string SignInButton {
            get {
                return ResourceManager.GetString("SignInButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string SignInLink {
            get {
                return ResourceManager.GetString("SignInLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string SignUp {
            get {
                return ResourceManager.GetString("SignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string SigninUnknownError {
            get {
                return ResourceManager.GetString("SigninUnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string Signout {
            get {
                return ResourceManager.GetString("Signout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string SignupHeading {
            get {
                return ResourceManager.GetString("SignupHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string SignupSubtitle {
            get {
                return ResourceManager.GetString("SignupSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string SignupUnknownError {
            get {
                return ResourceManager.GetString("SignupUnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string SinHacerLabel {
            get {
                return ResourceManager.GetString("SinHacerLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string SinResponderLabel {
            get {
                return ResourceManager.GetString("SinResponderLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string StartSimulation {
            get {
                return ResourceManager.GetString("StartSimulation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string StatsSummaryFormat {
            get {
                return ResourceManager.GetString("StatsSummaryFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string StatusApto {
            get {
                return ResourceManager.GetString("StatusApto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string StatusEmpezado {
            get {
                return ResourceManager.GetString("StatusEmpezado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string StatusNoApto {
            get {
                return ResourceManager.GetString("StatusNoApto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string TabProfile {
            get {
                return ResourceManager.GetString("TabProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string TabStudy {
            get {
                return ResourceManager.GetString("TabStudy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string TabTests {
            get {
                return ResourceManager.GetString("TabTests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string TermsAndConditionsAgreement {
            get {
                return ResourceManager.GetString("TermsAndConditionsAgreement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string TopicCompleted {
            get {
                return ResourceManager.GetString("TopicCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string TopicErrorsAllowedFormat {
            get {
                return ResourceManager.GetString("TopicErrorsAllowedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string TopicErrorsNote {
            get {
                return ResourceManager.GetString("TopicErrorsNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string TopicSelectionDescription {
            get {
                return ResourceManager.GetString("TopicSelectionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string TopicSelectionOverline {
            get {
                return ResourceManager.GetString("TopicSelectionOverline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string TopicSelectionTitle {
            get {
                return ResourceManager.GetString("TopicSelectionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string TopicsHeroLabel {
            get {
                return ResourceManager.GetString("TopicsHeroLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string UnknownError {
            get {
                return ResourceManager.GetString("UnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string UnsavedOnFinishFormat {
            get {
                return ResourceManager.GetString("UnsavedOnFinishFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string UnsavedWarningFormat {
            get {
                return ResourceManager.GetString("UnsavedWarningFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string UseSocialSigninError {
            get {
                return ResourceManager.GetString("UseSocialSigninError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string UserBlocked {
            get {
                return ResourceManager.GetString("UserBlocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string UserDoesNotExistError {
            get {
                return ResourceManager.GetString("UserDoesNotExistError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string ValidateYourEmail {
            get {
                return ResourceManager.GetString("ValidateYourEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string ValidationCode {
            get {
                return ResourceManager.GetString("ValidationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string VerificationCode {
            get {
                return ResourceManager.GetString("VerificationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string YourLicenseLabel {
            get {
                return ResourceManager.GetString("YourLicenseLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string YourProgressInFormat {
            get {
                return ResourceManager.GetString("YourProgressInFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string YourProgressTitle {
            get {
                return ResourceManager.GetString("YourProgressTitle", resourceCulture);
            }
        }
    }
}
