// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NavigationES.Api.Data;

#nullable disable

namespace NavigationES.Api.Migrations
{
    [DbContext(typeof(NavigationESDbContext))]
    [Migration("20260823043925_PyCyTopics")]
    partial class PyCyTopics
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NavigationES.Api.Data.Entities.AnswerEntity", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ID"));

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("bit");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<long>("QuestionID")
                        .HasColumnType("bigint");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("ID");

                    b.HasIndex("QuestionID")
                        .IsUnique()
                        .HasFilter("[IsCorrect] = 1");

                    b.ToTable("Answers");
                });

            modelBuilder.Entity("NavigationES.Api.Data.Entities.ComunidadAutonomaEntity", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("ID");

                    b.ToTable("ComunidadesAutonomas");

                    b.HasData(
                        new
                        {
                            ID = 1L,
                            Name = "Andalucía"
                        },
                        new
                        {
                            ID = 2L,
                            Name = "Cantabria"
                        },
                        new
                        {
                            ID = 3L,
                            Name = "Cataluña"
                        },
                        new
                        {
                            ID = 4L,
                            Name = "Ciudad Autónoma de Ceuta"
                        },
                        new
                        {
                            ID = 5L,
                            Name = "Ciudad Autónoma de Melilla"
                        },
                        new
                        {
                            ID = 6L,
                            Name = "Comunidad de Madrid"
                        },
                        new
                        {
                            ID = 7L,
                            Name = "Comunidad Valenciana"
                        },
                        new
                        {
                            ID = 8L,
                            Name = "Galicia"
                        },
                        new
                        {
                            ID = 9L,
                            Name = "Islas Baleares"
                        },
                        new
                        {
                            ID = 10L,
                            Name = "Islas Canarias"
                        },
                        new
                        {
                            ID = 11L,
                            Name = "País Vasco"
                        },
                        new
                        {
                            ID = 12L,
                            Name = "Principado de Asturias"
                        },
                        new
                        {
                            ID = 13L,
                            Name = "Región de Murcia"
                        });
                });

            modelBuilder.Entity("NavigationES.Api.Data.Entities.ExamEntity", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ID"));

                    b.Property<long>("ComunidadAutonomaID")
                        .HasColumnType("bigint");

                    b.Property<long>("LicenseID")
                        .HasColumnType("bigint");

                    b.Property<string>("Model")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("Month")
                        .HasColumnType("int");

                    b.Property<string>("SourceFile")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("LicenseID");

                    b.HasIndex("ComunidadAutonomaID", "LicenseID", "Year", "Month");

                    b.ToTable("Exams");
                });

            modelBuilder.Entity("NavigationES.Api.Data.Entities.ExamQuestionEntity", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ID"));

                    b.Property<string>("Answer1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Answer2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Answer3")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Answer4")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CorrectIndex")
                        .HasColumnType("int");

                    b.Property<long>("ExamID")
                        .HasColumnType("bigint");

                    b.Property<int>("Position")
                        .HasColumnType("int");

                    b.Property<string>("QuestionImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("TopicID")
                        .HasColumnType("bigint");

                    b.HasKey("ID");

                    b.HasIndex("TopicID");

                    b.HasIndex("ExamID", "Position")
                        .IsUnique();

                    b.ToTable("ExamQuestions");
                });

            modelBuilder.Entity("NavigationES.Api.Data.Entities.ExamSessionAnswerEntity", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ID"));

                    b.Property<int>("ChosenIndex")
                        .HasColumnType("int");

                    b.Property<long>("ExamQuestionID")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("bit");

                    b.Property<long>("SessionID")
                        .HasColumnType("bigint");

                    b.HasKey("ID");

                    b.HasIndex("ExamQuestionID");

                    b.HasIndex("SessionID", "ExamQuestionID")
                        .IsUnique();

                    b.ToTable("ExamSessionAnswers");
                });

            modelBuilder.Entity("NavigationES.Api.Data.Entities.LicenseEntity", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ID"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int?>("ExamMinutes")
                        .HasColumnType("int");

                    b.Property<int?>("MaxTotalErrors")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ID");

                    b.ToTable("Licenses");

                    b.HasData(
                        new
                        {
                            ID = 1L,
                            Code = "PNB",
                            ExamMinutes = 45,
                            MaxTotalErrors = 10,
                            Name = "Patrón para Navegación Básica"
                        },
                        new
                        {
                            ID = 2L,
                            Code = "PER",
                            ExamMinutes = 90,
                            MaxTotalErrors = 13,
                            Name = "Patrón de Embarcaciones de Recreo"
                        },
                        new
                        {
                            ID = 3L,
                            Code = "PY",
                            ExamMinutes = 120,
                            Name = "Patrón de Yate"
                        },
                        new
                        {
                            ID = 4L,
                            Code = "CY",
                            Name = "Capitán de Yate"
                        });
                });

            modelBuilder.Entity("NavigationES.Api.Data.Entities.LicenseTopicEntity", b =>
                {
                    b.Property<long>("LicenseID")
                        .HasColumnType("bigint");

                    b.Property<long>("TopicID")
                        .HasColumnType("bigint");

                    b.Property<int?>("MaxErrors")
                        .HasColumnType("int");

                    b.Property<int>("QuestionsInExam")
                        .HasColumnType("int");

                    b.HasKey("LicenseID", "TopicID");

                    b.HasIndex("TopicID");

                    b.ToTable("LicenseTopics");

                    b.HasData(
                        new
                        {
                            LicenseID = 1L,
                            TopicID = 1L,
                            QuestionsInExam = 4
                        },
                        new
                        {
                            LicenseID = 1L,
                            TopicID = 2L,
                            QuestionsInExam = 2
                        },
                        new
                        {
                            LicenseID = 1L,
                            TopicID = 3L,
                            QuestionsInExam = 4
                        },
                        new
                        {
                            LicenseID = 1L,
                            TopicID = 4L,
                            QuestionsInExam = 2
                        },
                        new
                        {
                            LicenseID = 1L,
                            TopicID = 5L,
                            QuestionsInExam = 5
                        },
                        new
                        {
                            LicenseID = 1L,
                            TopicID = 6L,
                            QuestionsInExam = 10
                        },
                        new
                        {
                            LicenseID = 2L,
                            TopicID = 1L,
                            QuestionsInExam = 4
                        },
                        new
                        {
                            LicenseID = 2L,
                            TopicID = 2L,
                            QuestionsInExam = 2
                        },
                        new
                        {
                            LicenseID = 2L,
                            TopicID = 3L,
                            QuestionsInExam = 4
                        },
                        new
                        {
                            LicenseID = 2L,
                            TopicID = 4L,
                            QuestionsInExam = 2
                        },
                        new
                        {
                            LicenseID = 2L,
                            TopicID = 5L,
                            MaxErrors = 2,
                            QuestionsInExam = 5
                        },
                        new
                        {
                            LicenseID = 2L,
                            TopicID = 6L,
                            MaxErrors = 5,
                            QuestionsInExam = 10
                        },
                        new
                        {
                            LicenseID = 2L,
                            TopicID = 7L,
                            QuestionsInExam = 2
                        },
                        new
                        {
                            LicenseID = 2L,
                            TopicID = 8L,
                            QuestionsInExam = 3
                        },
                        new
                        {
                            LicenseID = 2L,
                            TopicID = 9L,
                            QuestionsInExam = 4
                        },
                        new
                        {
                            LicenseID = 2L,
                            TopicID = 10L,
                            QuestionsInExam = 5
                        },
                        new
                        {
                            LicenseID = 2L,
                            TopicID = 11L,
                            MaxErrors = 2,
                            QuestionsInExam = 4
                        },
                        new
                        {
                            LicenseID = 3L,
                            TopicID = 12L,
                            QuestionsInExam = 10
                        },
                        new
                        {
                            LicenseID = 3L,
                            TopicID = 13L,
                            QuestionsInExam = 10
                        },
                        new
                        {
                            LicenseID = 3L,
                            TopicID = 14L,
                            QuestionsInExam = 10
                        },
                        new
                        {
                            LicenseID = 3L,
                            TopicID = 15L,
                            QuestionsInExam = 10
                        },
                        new
                        {
                            LicenseID = 4L,
                            TopicID = 16L,
                            QuestionsInExam = 10
                        },
                        new
                        {
                            LicenseID = 4L,
                            TopicID = 17L,
                            QuestionsInExam = 10
                        },
                        new
                        {
                            LicenseID = 4L,
                            TopicID = 18L,
                            QuestionsInExam = 10
                        },
                        new
                        {
                            LicenseID = 4L,
                            TopicID = 19L,
                            QuestionsInExam = 10
                        });
                });

            modelBuilder.Entity("NavigationES.Api.Data.Entities.PasswordResetTokenEntity", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Expiration")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("bit");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("UserID")
                        .HasColumnType("bigint");

                    b.HasKey("ID");

                    b.HasIndex("UserID");

                    b.ToTable("PasswordResetTokens");
                });

            modelBuilder.Entity("NavigationES.Api.Data.Entities.QuestionEntity", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ID"));

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Explanation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExplanationImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("QuestionImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("SourceExam")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("TopicID")
                        .HasColumnType("bigint");

                    b.HasKey("ID");

                    b.HasIndex("ContentHash")
                        .IsUnique();

                    b.HasIndex("TopicID");

                    b.ToTable("Questions");
                });

            modelBuilder.Entity("NavigationES.Api.Data.Entities.SessionAnswerEntity", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ID"));

                    b.Property<long?>("ChosenAnswerID")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("bit");

                    b.Property<long>("QuestionID")
                        .HasColumnType("bigint");

                    b.Property<long>("SessionID")
                        .HasColumnType("bigint");

                    b.HasKey("ID");

                    b.HasIndex("ChosenAnswerID");

                    b.HasIndex("QuestionID");

                    b.HasIndex("SessionID", "QuestionID")
                        .IsUnique();

                    b.ToTable("SessionAnswers");
                });

            modelBuilder.Entity("NavigationES.Api.Data.Entities.SessionQuestionEntity", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ID"));

                    b.Property<long>("QuestionID")
                        .HasColumnType("bigint");

                    b.Property<long>("SessionID")
                        .HasColumnType("bigint");

                    b.HasKey("ID");

                    b.HasIndex("QuestionID");

                    b.HasIndex("SessionID", "QuestionID")
                        .IsUnique();

                    b.ToTable("SessionQuestions");
                });

            modelBuilder.Entity("NavigationES.Api.Data.Entities.TestSessionEntity", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ID"));

                    b.Property<long?>("ExamID")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("datetime2");

                    b.Property<long>("LicenseID")
                        .HasColumnType("bigint");

                    b.Property<int>("Mode")
                        .HasColumnType("int");

                    b.Property<bool?>("Passed")
                        .HasColumnType("bit");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("datetime2");

                    b.Property<long?>("TopicID")
                        .HasColumnType("bigint");

                    b.Property<long>("UserID")
                        .HasColumnType("bigint");

                    b.HasKey("ID");

                    b.HasIndex("ExamID");

                    b.HasIndex("LicenseID");

                    b.HasIndex("TopicID");

                    b.HasIndex("UserID");

                    b.ToTable("TestSessions");
                });

            modelBuilder.Entity("NavigationES.Api.Data.Entities.TopicEntity", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("Number")
                        .IsUnique();

                    b.ToTable("Topics");

                    b.HasData(
                        new
                        {
                            ID = 1L,
                            Name = "Nomenclatura náutica",
                            Number = 1
                        },
                        new
                        {
                            ID = 2L,
                            Name = "Elementos de amarre y fondeo",
                            Number = 2
                        },
                        new
                        {
                            ID = 3L,
                            Name = "Seguridad",
                            Number = 3
                        },
                        new
                        {
                            ID = 4L,
                            Name = "Legislación",
                            Number = 4
                        },
                        new
                        {
                            ID = 5L,
                            Name = "Balizamiento",
                            Number = 5
                        },
                        new
                        {
                            ID = 6L,
                            Name = "Reglamento (RIPA)",
                            Number = 6
                        },
                        new
                        {
                            ID = 7L,
                            Name = "Maniobra y navegación",
                            Number = 7
                        },
                        new
                        {
                            ID = 8L,
                            Name = "Emergencias en la mar",
                            Number = 8
                        },
                        new
                        {
                            ID = 9L,
                            Name = "Meteorología",
                            Number = 9
                        },
                        new
                        {
                            ID = 10L,
                            Name = "Teoría de la navegación",
                            Number = 10
                        },
                        new
                        {
                            ID = 11L,
                            Name = "Carta de navegación",
                            Number = 11
                        },
                        new
                        {
                            ID = 12L,
                            Name = "Seguridad en la mar (PY)",
                            Number = 12
                        },
                        new
                        {
                            ID = 13L,
                            Name = "Meteorología (PY)",
                            Number = 13
                        },
                        new
                        {
                            ID = 14L,
                            Name = "Teoría de navegación (PY)",
                            Number = 14
                        },
                        new
                        {
                            ID = 15L,
                            Name = "Navegación carta (PY)",
                            Number = 15
                        },
                        new
                        {
                            ID = 16L,
                            Name = "Meteorología (CY)",
                            Number = 16
                        },
                        new
                        {
                            ID = 17L,
                            Name = "Inglés (CY)",
                            Number = 17
                        },
                        new
                        {
                            ID = 18L,
                            Name = "Teoría de navegación (CY)",
                            Number = 18
                        },
                        new
                        {
                            ID = 19L,
                            Name = "Cálculo de navegación (CY)",
                            Number = 19
                        });
                });

            modelBuilder.Entity("NavigationES.Api.Data.Entities.UserEntity", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ID"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("EmailVerificationCode")
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<DateTime?>("EmailVerificationExpiry")
                        .HasColumnType("datetime2");

                    b.Property<string>("Hash")
                        .HasMaxLength(180)
                        .HasColumnType("nvarchar(180)");

                    b.Property<bool>("IsEmailVerified")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Salt")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<long?>("SelectedComunidadAutonomaID")
                        .HasColumnType("bigint");

                    b.Property<long?>("SelectedLicenseID")
                        .HasColumnType("bigint");

                    b.HasKey("ID");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique();

                    b.HasIndex("SelectedComunidadAutonomaID");

                    b.HasIndex("SelectedLicenseID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("NavigationES.Api.Data.Entities.UserLoginEntity", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("ProviderKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("RefreshToken")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<long>("UserID")
                        .HasColumnType("bigint");

                    b.HasKey("ID");

                    b.HasIndex("UserID");

                    b.HasIndex("Provider", "ProviderKey")
                        .IsUnique();

                    b.ToTable("UserLogins");
                });

            modelBuilder.Entity("NavigationES.Api.Data.Entities.AnswerEntity", b =>
                {
                    b.HasOne("NavigationES.Api.Data.Entities.QuestionEntity", "Question")
                        .WithMany("Answers")
                        .HasForeignKey("QuestionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("NavigationES.Api.Data.Entities.ExamEntity", b =>
                {
                    b.HasOne("NavigationES.Api.Data.Entities.ComunidadAutonomaEntity", "ComunidadAutonoma")
                        .WithMany()
                        .HasForeignKey("ComunidadAutonomaID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NavigationES.Api.Data.Entities.LicenseEntity", "License")
                        .WithMany()
                        .HasForeignKey("LicenseID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ComunidadAutonoma");

                    b.Navigation("License");
                });

            modelBuilder.Entity("NavigationES.Api.Data.Entities.ExamQuestionEntity", b =>
                {
                    b.HasOne("NavigationES.Api.Data.Entities.ExamEntity", "Exam")
                        .WithMany()
                        .HasForeignKey("ExamID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NavigationES.Api.Data.Entities.TopicEntity", "Topic")
                        .WithMany()
                        .HasForeignKey("TopicID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Exam");

                    b.Navigation("Topic");
                });

            modelBuilder.Entity("NavigationES.Api.Data.Entities.ExamSessionAnswerEntity", b =>
                {
                    b.HasOne("NavigationES.Api.Data.Entities.ExamQuestionEntity", "ExamQuestion")
                        .WithMany()
                        .HasForeignKey("ExamQuestionID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NavigationES.Api.Data.Entities.TestSessionEntity", "Session")
                        .WithMany()
                        .HasForeignKey("SessionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExamQuestion");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("NavigationES.Api.Data.Entities.LicenseTopicEntity", b =>
                {
                    b.HasOne("NavigationES.Api.Data.Entities.LicenseEntity", "License")
                        .WithMany("Topics")
                        .HasForeignKey("LicenseID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NavigationES.Api.Data.Entities.TopicEntity", "Topic")
                        .WithMany()
                        .HasForeignKey("TopicID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("License");

                    b.Navigation("Topic");
                });

            modelBuilder.Entity("NavigationES.Api.Data.Entities.PasswordResetTokenEntity", b =>
                {
                    b.HasOne("NavigationES.Api.Data.Entities.UserEntity", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("NavigationES.Api.Data.Entities.QuestionEntity", b =>
                {
                    b.HasOne("NavigationES.Api.Data.Entities.TopicEntity", "Topic")
                        .WithMany()
                        .HasForeignKey("TopicID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Topic");
                });

            modelBuilder.Entity("NavigationES.Api.Data.Entities.SessionAnswerEntity", b =>
                {
                    b.HasOne("NavigationES.Api.Data.Entities.AnswerEntity", "ChosenAnswer")
                        .WithMany()
                        .HasForeignKey("ChosenAnswerID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("NavigationES.Api.Data.Entities.QuestionEntity", "Question")
                        .WithMany()
                        .HasForeignKey("QuestionID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NavigationES.Api.Data.Entities.TestSessionEntity", "Session")
                        .WithMany()
                        .HasForeignKey("SessionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChosenAnswer");

                    b.Navigation("Question");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("NavigationES.Api.Data.Entities.SessionQuestionEntity", b =>
                {
                    b.HasOne("NavigationES.Api.Data.Entities.QuestionEntity", "Question")
                        .WithMany()
                        .HasForeignKey("QuestionID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NavigationES.Api.Data.Entities.TestSessionEntity", "Session")
                        .WithMany()
                        .HasForeignKey("SessionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("NavigationES.Api.Data.Entities.TestSessionEntity", b =>
                {
                    b.HasOne("NavigationES.Api.Data.Entities.ExamEntity", "Exam")
                        .WithMany()
                        .HasForeignKey("ExamID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("NavigationES.Api.Data.Entities.LicenseEntity", "License")
                        .WithMany()
                        .HasForeignKey("LicenseID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NavigationES.Api.Data.Entities.TopicEntity", "Topic")
                        .WithMany()
                        .HasForeignKey("TopicID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("NavigationES.Api.Data.Entities.UserEntity", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exam");

                    b.Navigation("License");

                    b.Navigation("Topic");

                    b.Navigation("User");
                });

            modelBuilder.Entity("NavigationES.Api.Data.Entities.UserEntity", b =>
                {
                    b.HasOne("NavigationES.Api.Data.Entities.ComunidadAutonomaEntity", null)
                        .WithMany()
                        .HasForeignKey("SelectedComunidadAutonomaID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("NavigationES.Api.Data.Entities.LicenseEntity", null)
                        .WithMany()
                        .HasForeignKey("SelectedLicenseID")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("NavigationES.Api.Data.Entities.UserLoginEntity", b =>
                {
                    b.HasOne("NavigationES.Api.Data.Entities.UserEntity", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("NavigationES.Api.Data.Entities.LicenseEntity", b =>
                {
                    b.Navigation("Topics");
                });

            modelBuilder.Entity("NavigationES.Api.Data.Entities.QuestionEntity", b =>
                {
                    b.Navigation("Answers");
                });
#pragma warning restore 612, 618
        }
    }
}
